### PR TITLE
Use new v2 api endpoint

### PR DESCRIPTION
**Pull request by Razzeee**
Change to the new endpoint for better performance and tracking as stated in https://plus.google.com/u/0/109991097847241028373/posts/iVkHY4MhhTF?cfem=1

### CODE REVIEW

**Comment by fuzeman** [comment]
Hopefully this fixes the periodic stream of 5xx errors :smiley:

**Comment by anaconda** [comment]
Just a note - both resolve to the same IPs here:
```
anepu:~ anaconda$ host api.trakt.tv
api.trakt.tv has address 198.41.205.42
api.trakt.tv has address 198.41.204.42
anepu:~ anaconda$ host api-v2launch.trakt.tv
api-v2launch.trakt.tv has address 198.41.205.42
api-v2launch.trakt.tv has address 198.41.204.42
```

I'm not saying this shouldn't have been merged, but unfortunately it seems it's unlikely to perform any better :-(

**Comment by Razzeee** [comment]
Yes, they do for now. But there will be more servers behind the new one and also it's easier to track v1 vs v2 for the trakt devs. As v1 is pulling down the performance of everybody right now.

**Comment by anaconda** [comment]
> Yes, they do for now. But there will be more servers behind the new one and also it's easier to track v1 vs v2 for the trakt devs. As v1 is pulling down the performance of everybody right now.
Ahh okay. Sorry for the noise (^2) then. I get a “post not found” error for your link, so I had to guess :-)

**Comment by Razzeee** [comment]
As I see that, would it be possible to create a staging mode? @fuzeman

**Comment by fuzeman** [comment]
198.41.205.42 is just the cloudflare proxy, beyond that it is likely routed to separate trakt.tv servers.

@Razzeee you should be able to switch to the staging server by doing this:
```python
Trakt.base_url = 'https://api.staging.trakt.tv'
```

**Comment by Razzeee** [comment]
That should work for me, but when I wrote that one above I jumped to more of a config kind of thing.
And just to let you know, I just switched to the new one after debugging with the old one this whole evening. Episodes were fucking slow, it already feels faster.

**Comment by s7eele** [comment]
>Hopefully this fixes the periodic stream of 5xx errors :smiley:

>Episodes were fucking slow, it already feels faster.

seems to have improved things pretty significantly (imho) :-)

**Comment by Razzeee** [comment]
Yep, but the new info we got means that even one 500+ error is very bad.

**Pull request merged**
