### PR TITLE
Retry handling in case of connection errors

### PR DESCRIPTION
**Pull request by vishal8492**
Retry handling in case of connection errors ; google DNS sometimes fail with initial tries.This helps to counter these quirks.
As @Razzeee suggested creating pull request here.

### CODE REVIEW

**Comment by fuzeman** [comment]
Connection retrying was enabled in requests/urllib3 recently (https://github.com/fuzeman/trakt.py/commit/713a32d580886f9724da60610a26e32e7dcd17b4), we shouldn't need to handle this in trakt.py itself.

Were you still getting connection errors on the latest version of script.trakt?

**Comment by vishal8492** [comment]
Hi,

Encountering these issues with latest commits from following branch ; not
sure how to synch to latest script.trakt. Your branch has just trakt.py.

Am I missing something?

https://github.com/Razzeee/script.trakt

**Comment by fuzeman** [comment]
The updated version of trakt.py is available on the master branch of https://github.com/Razzeee/script.trakt, you just need to either `git pull` or update from https://github.com/Razzeee/script.trakt/archive/master.zip

The xbmc/kodi log file might be helpful if there is still a problem after updating.

**Comment by fuzeman** [comment]
Just did some tests to make sure connection retrying does actually work (simulated DNS packet dropping with [clumsy](https://jagt.github.io/clumsy/)), it appears to be working correctly:
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.trakt.tv
WARNING:requests.packages.urllib3.connectionpool:Retrying (3 attempts remain) after connection broken by 'gaierror(11001, 'getaddrinfo failed')': /sync/watched/shows
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): api.trakt.tv
WARNING:requests.packages.urllib3.connectionpool:Retrying (2 attempts remain) after connection broken by 'gaierror(11001, 'getaddrinfo failed')': /sync/watched/shows
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3): api.trakt.tv
WARNING:requests.packages.urllib3.connectionpool:Retrying (1 attempts remain) after connection broken by 'gaierror(11001, 'getaddrinfo failed')': /sync/watched/shows
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4): api.trakt.tv
DEBUG:requests.packages.urllib3.connectionpool:"GET /sync/watched/shows HTTP/1.1" 200 None
```

We could increase the number of retries if needed.

**Comment by Razzeee** [comment]
The first two lines of this pull should not change anything from not working to working, if I understand them correct.
And please don't increase the number of retries, got the feeling its already quiet out of hand. Haven't tested, but feels like it. If my users change retries (default 1) to 5 for e.g. it will try for 5x3= 15 times if .we get timeouts (thats my suspicion). That does take quiet some time and it's not yet breaking then but trying to process the next item (thats something I have to fix)

**Comment by vishal8492** [comment]
Latest commit solves this issue ; couldn't reproduce same.So will close this pull request.Thanks for being so helpful.

**Comment by fuzeman** [comment]
@Razzeee it's probably not doing 5 (http.max_retries) x 3 (requests/urllib) retries, as trakt.py only retries on 5xx errors (not connection timeouts/errors).

The delay when encountering 5xx errors is likely to do with the ```time.sleep(5)``` between retries, with 5 retries this would result in a 25 second delay.. We could probably drop this a bit..

As `timeout` is currently set to `None` (wait forever for a response), this could cause quite a big delay as well.. Will need to work out a good default timeout value (and make it configurable).

**Comment by Razzeee** [comment]
@fuzeman 
yeah, timeouts should be a prio I think. I'm using 15 sec right now for the other parts of the trakt api I need to use

**Comment by Razzeee** [comment]
As it turns out it might be a pretty poisenous idea to retry after 500+  errors.
Check here. https://plus.google.com/u/0/109991097847241028373/posts/XW4CbfCgw2Q

**Comment by fuzeman** [comment]
I only enabled retrying on ```Trakt['auth'].login``` and the ```Trakt['scrobble']``` actions.

I've noticed 520 errors returned for ```/scrobble/stop``` does cause duplicate scrobbles when the request is retried.. this is a bit annoying..

**Comment by Razzeee** [comment]
Yep, it's pretty much hope that there is no error, if there is. Start all over from scratch :/

**Pull request closed without merging**
